export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const SEARCH_ID_REQUEST = 'SEARCH_ID_REQUEST';
export const SEARCH_ID_SUCCESS = 'SEARCH_ID_SUCCESS';
export const SEARCH_ID_FAILURE = 'SEARCH_ID_FAILURE';



